
players = ["Emily","Lucy"]   # players array
emily_rolls = 0   # accumulator
lucy_rolls = 0  # accumulator 
game_in_progress = true
# We can't use while true do as we just get an infinite output - 
# problematic - so we need a variable - a condition

# while true do   # while true 
while game_in_progress
  scores = []    # to keep a track of scores
  nums_generated = []    # to keep a track of numbers generated when dice rolled
  
  players.each { |player|   # iterate through the players array and print the
  # name of first player rolls:
    print "\n#{player} rolls: "   
    # then 2 times - we will push the number generated by rand into the
    # nums_generated array
    2.times {                    
      nums_generated.push (rand(7))
      print "#{nums_generated[-1]} "
    } 
    # then push the two scores into the
    # scores array
    scores.push ( nums_generated[-1] + nums_generated[-2] )
  }

  # print what Emily got - the first number in array - position -2
  # print what Lucy got - the second number in array - position -1
  puts "\n\nEmily scored: #{scores[-2]} - Lucy scored: #{scores[-1]}" 
  
  if scores[-2] > scores[-1]
    # if emily's score > lucy's score - emily wins
    emily_rolls += 1
    print "Emily has won this round"
    game_in_progress = false if emily_rolls >= 2
    
  elsif scores[-2] < scores[-1]
    # if emily's score is less than lucy's score - lucy wins
    lucy_rolls += 1
    print "Lucy has won this round"
    game_in_progress = false if lucy_rolls >= 2

  elsif scores[-2] == scores[-1]
   # Logic in case of a tie
    puts "There has been a tie!!!"
  end

end




